<!DOCTYPE html>
<html>
<head>
	<title>Command List | Stand</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link href="/halfmoon-variables.min.css" crossorigin="anonymous" rel="stylesheet" />
	<link href="/halfmoon-config.css" rel="stylesheet" />
</head>
<body class="dark-mode">
	<div class="page-wrapper with-navbar">
		<nav class="navbar">
			<div class="container-xl">
				<a class="navbar-brand" href="/">Stand</a>
				<ul class="navbar-nav">
					<li class="nav-item"><a class="nav-link" href="/account/">Account</a></li>
					<li class="nav-item active"><a class="nav-link" href="/help/">Help</a></li>
				</ul>
			</div>
		</nav>
		<div class="content-wrapper">
			<div class="container-xl">
				<div class="content">
					<h1>Stand Command List</h1>
					<p>What follows is a list of all commands available in <b>Stand 26.7.2</b>, generated by using <b>Stand &gt; Generate Features (en).txt</b>.</p>
					<p><a href="/components/command-list.txt" class="btn" target="_blank">Open in a new tab</a></p>
				</div>
				<div class="content">
					<pre class="overflow-x-scroll"><?php require "../components/command-list.txt"; ?></pre>
				</div>
			</div>
		</div>
	</div>
</body>
</html>
