#include "vehicle_items.hpp"

#include "atStringHash.hpp"

namespace Stand
{
	VehicleItem::VehicleItem(const char* name, const char* manufacturer, hash_t clazz, OnlineVersion&& dlc)
		: hash_name(name), name(name), manufacturer(manufacturer), clazz(clazz), dlc(std::move(dlc))
	{
	}

	const VehicleItem* VehicleItem::fromHash(const hash_t hash) noexcept
	{
		for (const VehicleItem& item : vehicle_items)
		{
			if (rage::atStringHash(item.hash_name) == hash)
			{
				return &item;
			}
		}
		return nullptr;
	}

	extern const VehicleItem vehicle_items[] = {
		//{"arbitergt", "imponte", ATSTRINGHASH("muscle"), "1.61 The Criminal Enterprises"},
		//{"astron2", "pfister", ATSTRINGHASH("suv"), "1.61 The Criminal Enterprises"},
		//{"cyclone2", "coil", ATSTRINGHASH("super"), "1.61 The Criminal Enterprises"},
		//{"ignus2", "pegassi", ATSTRINGHASH("super"), "1.61 The Criminal Enterprises"},
		//{"s95", "karin", ATSTRINGHASH("sport"), "1.61 The Criminal Enterprises"},
		{"adder", "truffade", ATSTRINGHASH("super"), "1.01 Game Launch"},
		{"airbus", "", ATSTRINGHASH("service"), "1.01 Game Launch"},
		{"airtug", "", ATSTRINGHASH("utility"), "1.01 Game Launch"},
		{"akula", "", ATSTRINGHASH("helicopter"), "1.42 The Doomsday Heist"},
		{"akuma", "dinka", ATSTRINGHASH("motorcycle"), "1.01 Game Launch"},
		{"aleutian", "vapid", ATSTRINGHASH("suv"), "1.68 The Chop Shop"},
		{"alkonost", "", ATSTRINGHASH("plane"), "1.52 Cayo Perico Heist"},
		{"alpha", "albany", ATSTRINGHASH("sport"), "1.11 Business"},
		{"alphaz1", "bucking", ATSTRINGHASH("plane"), "1.41 Smuggler's Run"},
		{"ambulance", "", ATSTRINGHASH("emergency"), "1.01 Game Launch"},
		{"annihilator", "", ATSTRINGHASH("helicopter"), "1.01 Game Launch"},
		{"annihilator2", "", ATSTRINGHASH("helicopter"), "1.52 Cayo Perico Heist"},
		{"apc", "hvy", ATSTRINGHASH("military"), "1.40 Gunrunning Pack"},
		{"ardent", "ocelot", ATSTRINGHASH("sport_classic"), "1.40 Gunrunning Pack"},
		{"armytanker", "", ATSTRINGHASH("utility"), "1.01 Game Launch"},
		{"armytrailer", "", ATSTRINGHASH("utility"), "1.01 Game Launch"},
		{"armytrailer2", "", ATSTRINGHASH("utility"), "1.01 Game Launch"},
		{"asbo", "maxwell", ATSTRINGHASH("compacts"), "1.49 Diamond Casino Heist"},
		{"asea", "declasse", ATSTRINGHASH("sedan"), "1.01 Game Launch"},
		{"asea2", "declasse", ATSTRINGHASH("sedan"), "1.01 Game Launch"},
		{"asterope", "karin", ATSTRINGHASH("sedan"), "1.01 Game Launch"},
		{"asterope2", "karin", ATSTRINGHASH("sedan"), "1.68 The Chop Shop"},
		{"astrale", "pfister", ATSTRINGHASH("sport_classic"), "1.72 A Safehouse in the Hills"},
		{"astron", "pfister", ATSTRINGHASH("suv"), "1.58 The Contract"},
		{"autarch", "overflod", ATSTRINGHASH("super"), "1.42 The Doomsday Heist"},
		{"avarus", "lcc", ATSTRINGHASH("motorcycle"), "1.36 Bikers"},
		{"avenger", "mammoth", ATSTRINGHASH("plane"), "1.42 The Doomsday Heist"},
		{"avenger2", "mammoth", ATSTRINGHASH("plane"), "1.42 The Doomsday Heist"},
		{"avenger3", "mammoth", ATSTRINGHASH("plane"), "1.67 San Andreas Mercenaries"},
		{"avenger4", "mammoth", ATSTRINGHASH("plane"), "1.67 San Andreas Mercenaries"},
		{"avisa", "kraken", ATSTRINGHASH("boat"), "1.52 Cayo Perico Heist"},
		{"bagger", "western", ATSTRINGHASH("motorcycle"), "1.01 Game Launch"},
		{"baletrailer", "", ATSTRINGHASH("utility"), "1.01 Game Launch"},
		{"baller", "gallivan", ATSTRINGHASH("suv"), "1.01 Game Launch"},
		{"baller2", "gallivan", ATSTRINGHASH("suv"), "1.01 Game Launch"},
		{"baller3", "gallivan", ATSTRINGHASH("suv"), "1.31 Executives and Other Criminals"},
		{"baller4", "gallivan", ATSTRINGHASH("suv"), "1.31 Executives and Other Criminals"},
		{"baller5", "gallivan", ATSTRINGHASH("suv"), "1.31 Executives and Other Criminals"},
		{"baller6", "gallivan", ATSTRINGHASH("suv"), "1.31 Executives and Other Criminals"},
		{"baller7", "gallivan", ATSTRINGHASH("suv"), "1.58 The Contract"},
		{"baller8", "gallivan", ATSTRINGHASH("suv"), "1.68 The Chop Shop"},
		{"banshee", "bravado", ATSTRINGHASH("sport"), "1.01 Game Launch"},
		{"banshee2", "bravado", ATSTRINGHASH("super"), "1.32 January 2016"},
		{"banshee3", "bravado", ATSTRINGHASH("sport"), "1.70 Agents of Sabotage"},
		{"barracks", "", ATSTRINGHASH("military"), "1.01 Game Launch"},
		{"barracks2", "hvy", ATSTRINGHASH("military"), "1.01 Game Launch"},
		{"barracks3", "", ATSTRINGHASH("military"), "1.21 Heists DLC"},
		{"barrage", "", ATSTRINGHASH("military"), "1.42 The Doomsday Heist"},
		{"bati", "pegassi", ATSTRINGHASH("motorcycle"), "1.01 Game Launch"},
		{"bati2", "pegassi", ATSTRINGHASH("motorcycle"), "1.01 Game Launch"},
		{"benson", "vapid", ATSTRINGHASH("commercial"), "1.01 Game Launch"},
		{"benson2", "vapid", ATSTRINGHASH("commercial"), "1.68 The Chop Shop"},
		{"besra", "western", ATSTRINGHASH("plane"), "1.16 SA Flight School"},
		{"bestiagts", "grotti", ATSTRINGHASH("sport"), "1.34 Further Adventures in Finance and Felony"},
		{"bf400", "nagasaki", ATSTRINGHASH("motorcycle"), "1.35 Cunning Stunts"},
		{"bfinjection", "bf", ATSTRINGHASH("off_road"), "1.01 Game Launch"},
		{"biff", "hvy", ATSTRINGHASH("commercial"), "1.01 Game Launch"},
		{"bifta", "bf", ATSTRINGHASH("off_road"), "1.06 Beach Bum"},
		{"bison", "bravado", ATSTRINGHASH("van"), "1.01 Game Launch"},
		{"bison2", "bravado", ATSTRINGHASH("van"), "1.01 Game Launch"},
		{"bison3", "bravado", ATSTRINGHASH("van"), "1.01 Game Launch"},
		{"bjxl", "karin", ATSTRINGHASH("suv"), "1.01 Game Launch"},
		{"blade", "vapid", ATSTRINGHASH("muscle"), "1.14 I'm Not a Hipster"},
		{"blazer", "nagasaki", ATSTRINGHASH("off_road"), "1.01 Game Launch"},
		{"blazer2", "nagasaki", ATSTRINGHASH("off_road"), "1.01 Game Launch"},
		{"blazer3", "nagasaki", ATSTRINGHASH("off_road"), "1.01 Game Launch"},
		{"blazer4", "nagasaki", ATSTRINGHASH("off_road"), "1.36 Bikers"},
		{"blazer5", "nagasaki", ATSTRINGHASH("off_road"), "1.37 Import/Export"},
		{"blimp", "", ATSTRINGHASH("plane"), "1.01 Game Launch"},
		{"blimp2", "", ATSTRINGHASH("plane"), "1.18 Next Gen Release"},
		{"blimp3", "", ATSTRINGHASH("plane"), "1.44 After Hours"},
		{"blista", "dinka", ATSTRINGHASH("compacts"), "1.01 Game Launch"},
		{"blista2", "dinka", ATSTRINGHASH("sport"), "1.18 Next Gen Release"},
		{"blista3", "dinka", ATSTRINGHASH("sport"), "1.18 Next Gen Release"},
		{"bmx", "", ATSTRINGHASH("cycle"), "1.01 Game Launch"},
		{"boattrailer", "", ATSTRINGHASH("utility"), "1.01 Game Launch"},
		{"boattrailer2", "", ATSTRINGHASH("utility"), "1.68 The Chop Shop"},
		{"boattrailer3", "", ATSTRINGHASH("utility"), "1.68 The Chop Shop"},
		{"bobcatxl", "vapid", ATSTRINGHASH("van"), "1.01 Game Launch"},
		{"bodhi2", "canis", ATSTRINGHASH("off_road"), "1.01 Game Launch"},
		{"bombushka", "", ATSTRINGHASH("plane"), "1.41 Smuggler's Run"},
		{"boor", "karin", ATSTRINGHASH("off_road"), "1.64 Drug Wars"},
		{"boxville", "brute", ATSTRINGHASH("van"), "1.01 Game Launch"},
		{"boxville2", "", ATSTRINGHASH("van"), "1.01 Game Launch"},
		{"boxville3", "brute", ATSTRINGHASH("van"), "1.01 Game Launch"},
		{"boxville4", "brute", ATSTRINGHASH("van"), "1.21 Heists DLC"},
		{"boxville5", "", ATSTRINGHASH("van"), "1.37 Import/Export"},
		{"boxville6", "brute", ATSTRINGHASH("van"), "1.68 The Chop Shop"},
		{"brawler", "coil", ATSTRINGHASH("off_road"), "1.28 Ill-Gotten Gains Part 2"},
		{"brickade", "mtl", ATSTRINGHASH("service"), "1.34 Further Adventures in Finance and Felony"},
		{"brickade2", "mtl", ATSTRINGHASH("service"), "1.64 Drug Wars"},
		{"brigham", "albany", ATSTRINGHASH("muscle"), "1.67 San Andreas Mercenaries"},
		{"brioso", "grotti", ATSTRINGHASH("compacts"), "1.35 Cunning Stunts"},
		{"brioso2", "grotti", ATSTRINGHASH("compacts"), "1.52 Cayo Perico Heist"},
		{"brioso3", "grotti", ATSTRINGHASH("compacts"), "1.61 The Criminal Enterprises"},
		{"broadway", "classique", ATSTRINGHASH("muscle"), "1.64 Drug Wars"},
		{"bruiser", "benefac", ATSTRINGHASH("off_road"), "1.46 Arena War"},
		{"bruiser2", "benefac", ATSTRINGHASH("off_road"), "1.46 Arena War"},
		{"bruiser3", "benefac", ATSTRINGHASH("off_road"), "1.46 Arena War"},
		{"brutus", "declasse", ATSTRINGHASH("off_road"), "1.46 Arena War"},
		{"brutus2", "declasse", ATSTRINGHASH("off_road"), "1.46 Arena War"},
		{"brutus3", "declasse", ATSTRINGHASH("off_road"), "1.46 Arena War"},
		{"btype", "albany", ATSTRINGHASH("sport_classic"), "1.10 Valentine's Day Massacre"},
		{"btype2", "albany", ATSTRINGHASH("sport_classic"), "1.30.1 Halloween Surprise"},
		{"btype3", "albany", ATSTRINGHASH("sport_classic"), "1.32.1 Be My Valentine"},
		{"buccaneer", "albany", ATSTRINGHASH("muscle"), "1.01 Game Launch"},
		{"buccaneer2", "albany", ATSTRINGHASH("muscle"), "1.30 Lowriders"},
		{"buffalo", "bravado", ATSTRINGHASH("sport"), "1.01 Game Launch"},
		{"buffalo2", "bravado", ATSTRINGHASH("sport"), "1.01 Game Launch"},
		{"buffalo3", "bravado", ATSTRINGHASH("sport"), "1.18 Next Gen Release"},
		{"buffalo4", "bravado", ATSTRINGHASH("muscle"), "1.58 The Contract"},
		{"buffalo5", "bravado", ATSTRINGHASH("muscle"), "1.67 San Andreas Mercenaries"},
		{"bulldozer", "hvy", ATSTRINGHASH("industrial"), "1.01 Game Launch"},
		{"bullet", "vapid", ATSTRINGHASH("super"), "1.01 Game Launch"},
		{"burrito", "declasse", ATSTRINGHASH("van"), "1.01 Game Launch"},
		{"burrito2", "declasse", ATSTRINGHASH("van"), "1.01 Game Launch"},
		{"burrito3", "declasse", ATSTRINGHASH("van"), "1.01 Game Launch"},
		{"burrito4", "declasse", ATSTRINGHASH("van"), "1.01 Game Launch"},
		{"burrito5", "declasse", ATSTRINGHASH("van"), "1.01 Game Launch"},
		{"bus", "", ATSTRINGHASH("service"), "1.01 Game Launch"},
		{"buzzard", "", ATSTRINGHASH("helicopter"), "1.01 Game Launch"},
		{"buzzard2", "", ATSTRINGHASH("helicopter"), "1.01 Game Launch"},
		{"cablecar", "", ATSTRINGHASH("rail"), "1.01 Game Launch"},
		{"caddy", "", ATSTRINGHASH("utility"), "1.01 Game Launch"},
		{"caddy2", "", ATSTRINGHASH("utility"), "1.01 Game Launch"},
		{"caddy3", "", ATSTRINGHASH("utility"), "1.40 Gunrunning Pack"},
		{"calico", "karin", ATSTRINGHASH("sport"), "1.57 LS Tuners"},
		{"camper", "brute", ATSTRINGHASH("van"), "1.01 Game Launch"},
		{"caracara", "vapid", ATSTRINGHASH("off_road"), "1.43 Southern SA Super Sport Series"},
		{"caracara2", "vapid", ATSTRINGHASH("off_road"), "1.48 Diamond Casino & Resort"},
		{"caracara3", "vapid", ATSTRINGHASH("off_road"), "1.73 The Kortz Center Heist"},
		{"carbonizzare", "grotti", ATSTRINGHASH("sport"), "1.01 Game Launch"},
		{"carbonrs", "nagasaki", ATSTRINGHASH("motorcycle"), "1.01 Game Launch"},
		{"cargobob", "", ATSTRINGHASH("helicopter"), "1.01 Game Launch"},
		{"cargobob2", "", ATSTRINGHASH("helicopter"), "1.01 Game Launch"},
		{"cargobob3", "", ATSTRINGHASH("helicopter"), "1.01 Game Launch"},
		{"cargobob4", "", ATSTRINGHASH("helicopter"), "1.31 Executives and Other Criminals"},
		{"cargobob5", "bucking", ATSTRINGHASH("helicopter"), "1.70 Agents of Sabotage"},
		{"cargoplane", "", ATSTRINGHASH("plane"), "1.01 Game Launch"},
		{"cargoplane2", "", ATSTRINGHASH("plane"), "1.64 Drug Wars"},
		{"cartuccia", "grotti", ATSTRINGHASH("sport"), "1.73 The Kortz Center Heist"},
		{"casco", "lampada", ATSTRINGHASH("sport_classic"), "1.21 Heists DLC"},
		{"castigator", "canis", ATSTRINGHASH("suv"), "1.69 Bottom Dollar Bounties"},
		{"cavalcade", "albany", ATSTRINGHASH("suv"), "1.01 Game Launch"},
		{"cavalcade2", "albany", ATSTRINGHASH("suv"), "1.01 Game Launch"},
		{"cavalcade3", "albany", ATSTRINGHASH("suv"), "1.68 The Chop Shop"},
		{"cerberus", "mtl", ATSTRINGHASH("commercial"), "1.46 Arena War"},
		{"cerberus2", "mtl", ATSTRINGHASH("commercial"), "1.46 Arena War"},
		{"cerberus3", "mtl", ATSTRINGHASH("commercial"), "1.46 Arena War"},
		{"champion", "dewbauch", ATSTRINGHASH("super"), "1.58 The Contract"},
		{"chavosv6", "dinka", ATSTRINGHASH("sedan"), "1.70 Agents of Sabotage"},
		{"cheburek", "rune", ATSTRINGHASH("sport_classic"), "1.43 Southern SA Super Sport Series"},
		{"cheetah", "grotti", ATSTRINGHASH("super"), "1.01 Game Launch"},
		{"cheetah2", "grotti", ATSTRINGHASH("sport_classic"), "1.40 Gunrunning Pack"},
		{"cheetah3", "grotti", ATSTRINGHASH("sport_classic"), "1.71 Money Fronts"},
		{"chernobog", "", ATSTRINGHASH("military"), "1.42 The Doomsday Heist"},
		{"chimera", "nagasaki", ATSTRINGHASH("motorcycle"), "1.36 Bikers"},
		{"chino", "vapid", ATSTRINGHASH("muscle"), "1.28 Ill-Gotten Gains Part 2"},
		{"chino2", "vapid", ATSTRINGHASH("muscle"), "1.30 Lowriders"},
		{"cinquemila", "lampada", ATSTRINGHASH("sedan"), "1.58 The Contract"},
		{"cliffhanger", "western", ATSTRINGHASH("motorcycle"), "1.35 Cunning Stunts"},
		{"clique", "vapid", ATSTRINGHASH("muscle"), "1.46 Arena War"},
		{"clique2", "vapid", ATSTRINGHASH("muscle"), "1.67 San Andreas Mercenaries"},
		{"club", "bf", ATSTRINGHASH("compacts"), "1.51 LS Summer Special"},
		{"coach", "", ATSTRINGHASH("service"), "1.01 Game Launch"},
		{"cog55", "enus", ATSTRINGHASH("sedan"), "1.31 Executives and Other Criminals"},
		{"cog552", "enus", ATSTRINGHASH("sedan"), "1.31 Executives and Other Criminals"},
		{"cogcabrio", "enus", ATSTRINGHASH("coupe"), "1.01 Game Launch"},
		{"cognoscenti", "enus", ATSTRINGHASH("sedan"), "1.31 Executives and Other Criminals"},
		{"cognoscenti2", "enus", ATSTRINGHASH("sedan"), "1.31 Executives and Other Criminals"},
		{"comet2", "pfister", ATSTRINGHASH("sport"), "1.01 Game Launch"},
		{"comet3", "pfister", ATSTRINGHASH("sport"), "1.37 Import/Export"},
		{"comet4", "pfister", ATSTRINGHASH("sport"), "1.42 The Doomsday Heist"},
		{"comet5", "pfister", ATSTRINGHASH("sport"), "1.42 The Doomsday Heist"},
		{"comet6", "pfister", ATSTRINGHASH("sport"), "1.57 LS Tuners"},
		{"comet7", "pfister", ATSTRINGHASH("sport"), "1.58 The Contract"},
		{"conada", "bucking", ATSTRINGHASH("helicopter"), "1.61 The Criminal Enterprises"},
		{"conada2", "bucking", ATSTRINGHASH("helicopter"), "1.67 San Andreas Mercenaries"},
		{"contender", "vapid", ATSTRINGHASH("suv"), "1.35 Cunning Stunts"},
		{"coquette", "inverto", ATSTRINGHASH("sport"), "1.01 Game Launch"},
		{"coquette2", "inverto", ATSTRINGHASH("sport_classic"), "1.16 SA Flight School"},
		{"coquette3", "inverto", ATSTRINGHASH("muscle"), "1.28 Ill-Gotten Gains Part 2"},
		{"coquette4", "inverto", ATSTRINGHASH("sport"), "1.51 LS Summer Special"},
		{"coquette5", "inverto", ATSTRINGHASH("sport_classic"), "1.69 Bottom Dollar Bounties"},
		{"coquette6", "inverto", ATSTRINGHASH("sport"), "1.70 Agents of Sabotage"},
		{"corsita", "lampada", ATSTRINGHASH("sport"), "1.61 The Criminal Enterprises"},
		{"coureur", "penaud", ATSTRINGHASH("sport"), "1.67 San Andreas Mercenaries"},
		{"cruiser", "", ATSTRINGHASH("cycle"), "1.01 Game Launch"},
		{"crusader", "canis", ATSTRINGHASH("military"), "1.01 Game Launch"},
		{"cuban800", "", ATSTRINGHASH("plane"), "1.01 Game Launch"},
		{"cutter", "hvy", ATSTRINGHASH("industrial"), "1.01 Game Launch"},
		{"cyclone", "coil", ATSTRINGHASH("super"), "1.41 Smuggler's Run"},
		{"cypher", "ubermacht", ATSTRINGHASH("sport"), "1.57 LS Tuners"},
		{"daemon", "western", ATSTRINGHASH("motorcycle"), "1.01 Game Launch"},
		{"daemon2", "western", ATSTRINGHASH("motorcycle"), "1.36 Bikers"},
		{"deathbike", "western", ATSTRINGHASH("motorcycle"), "1.46 Arena War"},
		{"deathbike2", "western", ATSTRINGHASH("motorcycle"), "1.46 Arena War"},
		{"deathbike3", "western", ATSTRINGHASH("motorcycle"), "1.46 Arena War"},
		{"defiler", "shitzu", ATSTRINGHASH("motorcycle"), "1.36 Bikers"},
		{"deity", "enus", ATSTRINGHASH("sedan"), "1.58 The Contract"},
		{"deluxo", "imponte", ATSTRINGHASH("sport_classic"), "1.42 The Doomsday Heist"},
		{"deveste", "principl", ATSTRINGHASH("super"), "1.46 Arena War"},
		{"deviant", "schyster", ATSTRINGHASH("muscle"), "1.46 Arena War"},
		{"diablous", "principl", ATSTRINGHASH("motorcycle"), "1.37 Import/Export"},
		{"diablous2", "principl", ATSTRINGHASH("motorcycle"), "1.37 Import/Export"},
		{"dilettante", "karin", ATSTRINGHASH("compacts"), "1.01 Game Launch"},
		{"dilettante2", "karin", ATSTRINGHASH("compacts"), "1.01 Game Launch"},
		{"dinghy", "nagasaki", ATSTRINGHASH("boat"), "1.01 Game Launch"},
		{"dinghy2", "nagasaki", ATSTRINGHASH("boat"), "1.01 Game Launch"},
		{"dinghy3", "nagasaki", ATSTRINGHASH("boat"), "1.21 Heists DLC"},
		{"dinghy4", "nagasaki", ATSTRINGHASH("boat"), "1.31 Executives and Other Criminals"},
		{"dinghy5", "nagasaki", ATSTRINGHASH("boat"), "1.52 Cayo Perico Heist"},
		{"dloader", "bravado", ATSTRINGHASH("off_road"), "1.01 Game Launch"},
		{"docktrailer", "", ATSTRINGHASH("utility"), "1.01 Game Launch"},
		{"docktug", "", ATSTRINGHASH("utility"), "1.01 Game Launch"},
		{"dodo", "mammoth", ATSTRINGHASH("plane"), "1.18 Next Gen Release"},
		{"dominator", "vapid", ATSTRINGHASH("muscle"), "1.01 Game Launch"},
		{"dominator10", "vapid", ATSTRINGHASH("muscle"), "1.69 Bottom Dollar Bounties"},
		{"dominator2", "vapid", ATSTRINGHASH("muscle"), "1.18 Next Gen Release"},
		{"dominator3", "vapid", ATSTRINGHASH("muscle"), "1.43 Southern SA Super Sport Series"},
		{"dominator4", "vapid", ATSTRINGHASH("muscle"), "1.46 Arena War"},
		{"dominator5", "vapid", ATSTRINGHASH("muscle"), "1.46 Arena War"},
		{"dominator6", "vapid", ATSTRINGHASH("muscle"), "1.46 Arena War"},
		{"dominator7", "vapid", ATSTRINGHASH("muscle"), "1.57 LS Tuners"},
		{"dominator8", "vapid", ATSTRINGHASH("muscle"), "1.57 LS Tuners"},
		{"dominator9", "vapid", ATSTRINGHASH("muscle"), "1.68 The Chop Shop"},
		{"dorado", "bravado", ATSTRINGHASH("suv"), "1.68 The Chop Shop"},
		{"double", "dinka", ATSTRINGHASH("motorcycle"), "1.01 Game Launch"},
		{"drafter", "obey", ATSTRINGHASH("sport"), "1.48 Diamond Casino & Resort"},
		{"draugur", "declasse", ATSTRINGHASH("off_road"), "1.61 The Criminal Enterprises"},
		{"driftchavosv6", "dinka", ATSTRINGHASH("sedan"), "1.71 Money Fronts"},
		{"driftcheburek", "rune", ATSTRINGHASH("sport_classic"), "1.70 Agents of Sabotage"},
		{"driftcoquette", "inverto", ATSTRINGHASH("sport"), "1.73 The Kortz Center Heist"},
		{"driftcypher", "ubermacht", ATSTRINGHASH("sport"), "1.69 Bottom Dollar Bounties"},
		{"driftdominator10", "vapid", ATSTRINGHASH("muscle"), "1.71 Money Fronts"},
		{"driftdominator8", "vapid", ATSTRINGHASH("muscle"), "1.73 The Kortz Center Heist"},
		{"driftdominator9", "vapid", ATSTRINGHASH("muscle"), "1.72 A Safehouse in the Hills"},
		{"driftelegy", "annis", ATSTRINGHASH("sport"), "1.73 The Kortz Center Heist"},
		{"drifteuros", "annis", ATSTRINGHASH("sport"), "1.68 The Chop Shop"},
		{"driftfr36", "fathom", ATSTRINGHASH("coupe"), "1.68 The Chop Shop"},
		{"driftfuto", "karin", ATSTRINGHASH("sport"), "1.68 The Chop Shop"},
		{"driftfuto2", "karin", ATSTRINGHASH("sport"), "1.70 Agents of Sabotage"},
		{"driftgauntlet4", "bravado", ATSTRINGHASH("muscle"), "1.71 Money Fronts"},
		{"drifthardy", "annis", ATSTRINGHASH("sedan"), "1.71 Money Fronts"},
		{"driftjester", "dinka", ATSTRINGHASH("sport"), "1.68 The Chop Shop"},
		{"driftjester3", "dinka", ATSTRINGHASH("sport_classic"), "1.70 Agents of Sabotage"},
		{"driftkeitora", "shitzu", ATSTRINGHASH("utility"), "1.72 A Safehouse in the Hills"},
		{"driftl352", "declasse", ATSTRINGHASH("off_road"), "1.71 Money Fronts"},
		{"driftnebula", "vulcar", ATSTRINGHASH("sport_classic"), "1.69 Bottom Dollar Bounties"},
		{"driftremus", "annis", ATSTRINGHASH("sport"), "1.68 The Chop Shop"},
		{"driftrt3000", "dinka", ATSTRINGHASH("sport"), "1.72 A Safehouse in the Hills"},
		{"driftsentinel", "ubermach", ATSTRINGHASH("sport"), "1.69 Bottom Dollar Bounties"},
		{"driftsentinel2", "ubermach", ATSTRINGHASH("coupe"), "1.72 A Safehouse in the Hills"},
		{"drifttampa", "declasse", ATSTRINGHASH("sport"), "1.68 The Chop Shop"},
		{"driftvorschlag", "benefactor", ATSTRINGHASH("sedan"), "1.69 Bottom Dollar Bounties"},
		{"driftyosemite", "declasse", ATSTRINGHASH("muscle"), "1.68 The Chop Shop"},
		{"driftzr350", "annis", ATSTRINGHASH("sport"), "1.68 The Chop Shop"},
		{"dubsta", "benefac", ATSTRINGHASH("suv"), "1.01 Game Launch"},
		{"dubsta2", "benefac", ATSTRINGHASH("suv"), "1.01 Game Launch"},
		{"dubsta3", "benefac", ATSTRINGHASH("off_road"), "1.14 I'm Not a Hipster"},
		{"dukes", "imponte", ATSTRINGHASH("muscle"), "1.18 Next Gen Release"},
		{"dukes2", "imponte", ATSTRINGHASH("muscle"), "1.18 Next Gen Release"},
		{"dukes3", "imponte", ATSTRINGHASH("muscle"), "1.51 LS Summer Special"},
		{"dump", "hvy", ATSTRINGHASH("industrial"), "1.01 Game Launch"},
		{"dune", "bf", ATSTRINGHASH("off_road"), "1.01 Game Launch"},
		{"dune2", "", ATSTRINGHASH("off_road"), "1.01 Game Launch"},
		{"dune3", "bf", ATSTRINGHASH("off_road"), "1.40 Gunrunning Pack"},
		{"dune4", "", ATSTRINGHASH("off_road"), "1.37 Import/Export"},
		{"dune5", "", ATSTRINGHASH("off_road"), "1.37 Import/Export"},
		{"duster", "", ATSTRINGHASH("plane"), "1.01 Game Launch"},
		{"duster2", "western", ATSTRINGHASH("plane"), "1.70 Agents of Sabotage"},
		{"dynasty", "weeny", ATSTRINGHASH("sport_classic"), "1.48 Diamond Casino & Resort"},
		{"elegy", "annis", ATSTRINGHASH("sport"), "1.37 Import/Export"},
		{"elegy2", "annis", ATSTRINGHASH("sport"), "1.01 Game Launch"},
		{"ellie", "vapid", ATSTRINGHASH("muscle"), "1.43 Southern SA Super Sport Series"},
		{"emerus", "progen", ATSTRINGHASH("super"), "1.48 Diamond Casino & Resort"},
		{"emperor", "albany", ATSTRINGHASH("sedan"), "1.01 Game Launch"},
		{"emperor2", "albany", ATSTRINGHASH("sedan"), "1.01 Game Launch"},
		{"emperor3", "albany", ATSTRINGHASH("sedan"), "1.01 Game Launch"},
		{"enduro", "dinka", ATSTRINGHASH("motorcycle"), "1.21 Heists DLC"},
		{"entity2", "overflod", ATSTRINGHASH("super"), "1.43 Southern SA Super Sport Series"},
		{"entity3", "overflod", ATSTRINGHASH("super"), "1.64 Drug Wars"},
		{"entityxf", "overflod", ATSTRINGHASH("super"), "1.01 Game Launch"},
		{"envisage", "bollokan", ATSTRINGHASH("sport"), "1.69 Bottom Dollar Bounties"},
		{"esskey", "pegassi", ATSTRINGHASH("motorcycle"), "1.36 Bikers"},
		{"estride", "ocelot", ATSTRINGHASH("suv"), "1.73 The Kortz Center Heist"},
		{"eudora", "willard", ATSTRINGHASH("muscle"), "1.64 Drug Wars"},
		{"euros", "annis", ATSTRINGHASH("sport"), "1.57 LS Tuners"},
		{"eurosX32", "annis", ATSTRINGHASH("coupe"), "1.69 Bottom Dollar Bounties"},
		{"everon", "karin", ATSTRINGHASH("off_road"), "1.49 Diamond Casino Heist"},
		{"everon2", "karin", ATSTRINGHASH("sport"), "1.64 Drug Wars"},
		{"everon3", "karin", ATSTRINGHASH("suv"), "1.71 Money Fronts"},
		{"exemplar", "dewbauch", ATSTRINGHASH("coupe"), "1.01 Game Launch"},
		{"f620", "ocelot", ATSTRINGHASH("coupe"), "1.01 Game Launch"},
		{"faction", "willard", ATSTRINGHASH("muscle"), "1.30 Lowriders"},
		{"faction2", "willard", ATSTRINGHASH("muscle"), "1.30 Lowriders"},
		{"faction3", "willard", ATSTRINGHASH("muscle"), "1.33 Lowriders: Custom Classics"},
		{"fagaloa", "vulcar", ATSTRINGHASH("sport_classic"), "1.43 Southern SA Super Sport Series"},
		{"faggio", "pegassi", ATSTRINGHASH("motorcycle"), "1.36 Bikers"},
		{"faggio2", "pegassi", ATSTRINGHASH("motorcycle"), "1.01 Game Launch"},
		{"faggio3", "pegassi", ATSTRINGHASH("motorcycle"), "1.36 Bikers"},
		{"fbi", "", ATSTRINGHASH("emergency"), "1.01 Game Launch"},
		{"fbi2", "", ATSTRINGHASH("emergency"), "1.01 Game Launch"},
		{"fcr", "pegassi", ATSTRINGHASH("motorcycle"), "1.37 Import/Export"},
		{"fcr2", "pegassi", ATSTRINGHASH("motorcycle"), "1.37 Import/Export"},
		{"felon", "lampada", ATSTRINGHASH("coupe"), "1.01 Game Launch"},
		{"felon2", "lampada", ATSTRINGHASH("coupe"), "1.01 Game Launch"},
		{"feltzer2", "benefac", ATSTRINGHASH("sport"), "1.01 Game Launch"},
		{"feltzer3", "benefac", ATSTRINGHASH("sport_classic"), "1.27 Ill-Gotten Gains Part 1"},
		{"firebolt", "vapid", ATSTRINGHASH("off_road"), "1.70 Agents of Sabotage"},
		{"firetruk", "mtl", ATSTRINGHASH("emergency"), "1.01 Game Launch"},
		{"fixter", "", ATSTRINGHASH("cycle"), "1.01 Game Launch"},
		{"flashgt", "vapid", ATSTRINGHASH("sport"), "1.43 Southern SA Super Sport Series"},
		{"flatbed", "mtl", ATSTRINGHASH("industrial"), "1.01 Game Launch"},
		{"flatbed2", "mtl", ATSTRINGHASH("industrial"), "1.71 Money Fronts"},
		{"fmj", "vapid", ATSTRINGHASH("super"), "1.34 Further Adventures in Finance and Felony"},
		{"fmj2", "vapid", ATSTRINGHASH("super"), "1.72 A Safehouse in the Hills"},
		{"forklift", "hvy", ATSTRINGHASH("utility"), "1.01 Game Launch"},
		{"formula", "progen", ATSTRINGHASH("open_wheel"), "1.49 Diamond Casino Heist"},
		{"formula2", "ocelot", ATSTRINGHASH("open_wheel"), "1.49 Diamond Casino Heist"},
		{"fq2", "fathom", ATSTRINGHASH("suv"), "1.01 Game Launch"},
		{"fr36", "fathom", ATSTRINGHASH("coupe"), "1.68 The Chop Shop"},
		{"freecrawler", "canis", ATSTRINGHASH("off_road"), "1.44 After Hours"},
		{"freight", "", ATSTRINGHASH("rail"), "1.01 Game Launch"},
		{"freight2", "", ATSTRINGHASH("rail"), "1.68 The Chop Shop"},
		{"freightcar", "", ATSTRINGHASH("rail"), "1.01 Game Launch"},
		{"freightcar2", "", ATSTRINGHASH("rail"), "1.57 LS Tuners"},
		{"freightcar3", "", ATSTRINGHASH("rail"), "1.70 Agents of Sabotage"},
		{"freightcont1", "", ATSTRINGHASH("rail"), "1.01 Game Launch"},
		{"freightcont2", "", ATSTRINGHASH("rail"), "1.01 Game Launch"},
		{"freightgrain", "", ATSTRINGHASH("rail"), "1.01 Game Launch"},
		{"freighttrailer", "", ATSTRINGHASH("utility"), "1.01 Game Launch"},
		{"frogger", "", ATSTRINGHASH("helicopter"), "1.01 Game Launch"},
		{"frogger2", "", ATSTRINGHASH("helicopter"), "1.01 Game Launch"},
		{"fugitive", "cheval", ATSTRINGHASH("sedan"), "1.01 Game Launch"},
		{"furia", "grotti", ATSTRINGHASH("super"), "1.49 Diamond Casino Heist"},
		{"furoregt", "lampada", ATSTRINGHASH("sport"), "1.17 Last Team Standing"},
		{"fusilade", "schyster", ATSTRINGHASH("sport"), "1.01 Game Launch"},
		{"futo", "karin", ATSTRINGHASH("sport"), "1.01 Game Launch"},
		{"futo2", "karin", ATSTRINGHASH("sport"), "1.57 LS Tuners"},
		{"gargoyle", "western", ATSTRINGHASH("motorcycle"), "1.35 Cunning Stunts"},
		{"gauntlet", "bravado", ATSTRINGHASH("muscle"), "1.01 Game Launch"},
		{"gauntlet2", "bravado", ATSTRINGHASH("muscle"), "1.18 Next Gen Release"},
		{"gauntlet3", "bravado", ATSTRINGHASH("muscle"), "1.48 Diamond Casino & Resort"},
		{"gauntlet4", "bravado", ATSTRINGHASH("muscle"), "1.48 Diamond Casino & Resort"},
		{"gauntlet5", "bravado", ATSTRINGHASH("muscle"), "1.51 LS Summer Special"},
		{"gauntlet6", "bravado", ATSTRINGHASH("sport"), "1.67 San Andreas Mercenaries"},
		{"gb200", "vapid", ATSTRINGHASH("sport"), "1.43 Southern SA Super Sport Series"},
		{"gburrito", "declasse", ATSTRINGHASH("van"), "1.01 Game Launch"},
		{"gburrito2", "declasse", ATSTRINGHASH("van"), "1.21 Heists DLC"},
		{"glendale", "benefac", ATSTRINGHASH("sedan"), "1.14 I'm Not a Hipster"},
		{"glendale2", "benefac", ATSTRINGHASH("sedan"), "1.51 LS Summer Special"},
		{"gp1", "progen", ATSTRINGHASH("super"), "1.38 Special Vehicle Circuit"},
		{"graintrailer", "", ATSTRINGHASH("utility"), "1.01 Game Launch"},
		{"granger", "declasse", ATSTRINGHASH("suv"), "1.01 Game Launch"},
		{"granger2", "declasse", ATSTRINGHASH("suv"), "1.58 The Contract"},
		{"greenwood", "bravado", ATSTRINGHASH("muscle"), "1.61 The Criminal Enterprises"},
		{"gresley", "bravado", ATSTRINGHASH("suv"), "1.01 Game Launch"},
		{"growler", "pfister", ATSTRINGHASH("sport"), "1.57 LS Tuners"},
		{"gt500", "grotti", ATSTRINGHASH("sport_classic"), "1.42 The Doomsday Heist"},
		{"gt750", "grotti", ATSTRINGHASH("sport_classic"), "1.72 A Safehouse in the Hills"},
		{"guardian", "vapid", ATSTRINGHASH("industrial"), "1.21 Heists DLC"},
		{"habanero", "emperor", ATSTRINGHASH("suv"), "1.01 Game Launch"},
		{"hakuchou", "shitzu", ATSTRINGHASH("motorcycle"), "1.17 Last Team Standing"},
		{"hakuchou2", "shitzu", ATSTRINGHASH("motorcycle"), "1.36 Bikers"},
		{"halftrack", "bravado", ATSTRINGHASH("military"), "1.40 Gunrunning Pack"},
		{"handler", "", ATSTRINGHASH("industrial"), "1.01 Game Launch"},
		{"hardy", "annis", ATSTRINGHASH("sedan"), "1.71 Money Fronts"},
		{"hauler", "jobuilt", ATSTRINGHASH("commercial"), "1.01 Game Launch"},
		{"hauler2", "jobuilt", ATSTRINGHASH("commercial"), "1.40 Gunrunning Pack"},
		{"havok", "nagasaki", ATSTRINGHASH("helicopter"), "1.41 Smuggler's Run"},
		{"hellion", "annis", ATSTRINGHASH("off_road"), "1.48 Diamond Casino & Resort"},
		{"hermes", "albany", ATSTRINGHASH("muscle"), "1.42 The Doomsday Heist"},
		{"hexer", "lcc", ATSTRINGHASH("motorcycle"), "1.01 Game Launch"},
		{"horus", "pegassi", ATSTRINGHASH("super"), "1.73 The Kortz Center Heist"},
		{"hotknife", "vapid", ATSTRINGHASH("muscle"), "1.01 Game Launch"},
		{"hotring", "declasse", ATSTRINGHASH("sport"), "1.43 Southern SA Super Sport Series"},
		{"howard", "bucking", ATSTRINGHASH("plane"), "1.41 Smuggler's Run"},
		{"hunter", "", ATSTRINGHASH("helicopter"), "1.41 Smuggler's Run"},
		{"huntley", "enus", ATSTRINGHASH("suv"), "1.13 High Life"},
		{"hustler", "vapid", ATSTRINGHASH("muscle"), "1.42 The Doomsday Heist"},
		{"hydra", "mammoth", ATSTRINGHASH("plane"), "1.21 Heists DLC"},
		{"ignus", "pegassi", ATSTRINGHASH("super"), "1.58 The Contract"},
		{"imorgon", "overflod", ATSTRINGHASH("sport"), "1.49 Diamond Casino Heist"},
		{"impaler", "declasse", ATSTRINGHASH("muscle"), "1.46 Arena War"},
		{"impaler2", "declasse", ATSTRINGHASH("muscle"), "1.46 Arena War"},
		{"impaler3", "declasse", ATSTRINGHASH("muscle"), "1.46 Arena War"},
		{"impaler4", "declasse", ATSTRINGHASH("muscle"), "1.46 Arena War"},
		{"impaler5", "declasse", ATSTRINGHASH("sedan"), "1.68 The Chop Shop"},
		{"impaler6", "declasse", ATSTRINGHASH("muscle"), "1.68 The Chop Shop"},
		{"imperator", "vapid", ATSTRINGHASH("muscle"), "1.46 Arena War"},
		{"imperator2", "vapid", ATSTRINGHASH("muscle"), "1.46 Arena War"},
		{"imperator3", "vapid", ATSTRINGHASH("muscle"), "1.46 Arena War"},
		{"inductor", "", ATSTRINGHASH("cycle"), "1.67 San Andreas Mercenaries"},
		{"inductor2", "", ATSTRINGHASH("cycle"), "1.67 San Andreas Mercenaries"},
		{"infernus", "pegassi", ATSTRINGHASH("super"), "1.01 Game Launch"},
		{"infernus2", "pegassi", ATSTRINGHASH("sport_classic"), "1.38 Special Vehicle Circuit"},
		{"ingot", "vulcar", ATSTRINGHASH("sedan"), "1.01 Game Launch"},
		{"innovation", "lcc", ATSTRINGHASH("motorcycle"), "1.17 Last Team Standing"},
		{"insurgent", "hvy", ATSTRINGHASH("off_road"), "1.21 Heists DLC"},
		{"insurgent2", "hvy", ATSTRINGHASH("off_road"), "1.21 Heists DLC"},
		{"insurgent3", "hvy", ATSTRINGHASH("off_road"), "1.40 Gunrunning Pack"},
		{"intruder", "karin", ATSTRINGHASH("sedan"), "1.01 Game Launch"},
		{"issi2", "weeny", ATSTRINGHASH("compacts"), "1.01 Game Launch"},
		{"issi3", "weeny", ATSTRINGHASH("compacts"), "1.43 Southern SA Super Sport Series"},
		{"issi4", "weeny", ATSTRINGHASH("compacts"), "1.46 Arena War"},
		{"issi5", "weeny", ATSTRINGHASH("compacts"), "1.46 Arena War"},
		{"issi6", "weeny", ATSTRINGHASH("compacts"), "1.46 Arena War"},
		{"issi7", "weeny", ATSTRINGHASH("sport"), "1.48 Diamond Casino & Resort"},
		{"issi8", "weeny", ATSTRINGHASH("suv"), "1.64 Drug Wars"},
		{"itali2", "grotti", ATSTRINGHASH("sport_classic"), "1.72 A Safehouse in the Hills"},
		{"italigtb", "progen", ATSTRINGHASH("super"), "1.37 Import/Export"},
		{"italigtb2", "progen", ATSTRINGHASH("super"), "1.37 Import/Export"},
		{"italigto", "grotti", ATSTRINGHASH("sport"), "1.46 Arena War"},
		{"italirsx", "grotti", ATSTRINGHASH("sport"), "1.52 Cayo Perico Heist"},
		{"iwagen", "obey", ATSTRINGHASH("suv"), "1.58 The Contract"},
		{"jackal", "ocelot", ATSTRINGHASH("coupe"), "1.01 Game Launch"},
		{"jb700", "dewbauch", ATSTRINGHASH("sport_classic"), "1.01 Game Launch"},
		{"jb7002", "dewbauch", ATSTRINGHASH("sport_classic"), "1.49 Diamond Casino Heist"},
		{"jester", "dinka", ATSTRINGHASH("sport"), "1.11 Business"},
		{"jester2", "dinka", ATSTRINGHASH("sport"), "1.19 Festive Surprise 2014"},
		{"jester3", "dinka", ATSTRINGHASH("sport"), "1.43 Southern SA Super Sport Series"},
		{"jester4", "dinka", ATSTRINGHASH("sport"), "1.57 LS Tuners"},
		{"jester5", "dinka", ATSTRINGHASH("sport"), "1.70 Agents of Sabotage"},
		{"jet", "", ATSTRINGHASH("plane"), "1.01 Game Launch"},
		{"jetmax", "shitzu", ATSTRINGHASH("boat"), "1.01 Game Launch"},
		{"journey", "zirconiu", ATSTRINGHASH("van"), "1.01 Game Launch"},
		{"journey2", "zirconiu", ATSTRINGHASH("van"), "1.64 Drug Wars"},
		{"jubilee", "enus", ATSTRINGHASH("suv"), "1.58 The Contract"},
		{"jugular", "ocelot", ATSTRINGHASH("sport"), "1.48 Diamond Casino & Resort"},
		{"kalahari", "canis", ATSTRINGHASH("off_road"), "1.06 Beach Bum"},
		{"kamacho", "canis", ATSTRINGHASH("off_road"), "1.42 The Doomsday Heist"},
		{"kanjo", "dinka", ATSTRINGHASH("compacts"), "1.49 Diamond Casino Heist"},
		{"kanjosj", "dinka", ATSTRINGHASH("coupe"), "1.61 The Criminal Enterprises"},
		{"keitora", "shitzu", ATSTRINGHASH("utility"), "1.72 A Safehouse in the Hills"},
		{"khamelion", "hijak", ATSTRINGHASH("sport"), "1.01 Game Launch"},
		{"khanjali", "", ATSTRINGHASH("military"), "1.42 The Doomsday Heist"},
		{"komoda", "lampadati", ATSTRINGHASH("sport"), "1.49 Diamond Casino Heist"},
		{"kosatka", "rune", ATSTRINGHASH("boat"), "1.52 Cayo Perico Heist"},
		{"krieger", "benefactor", ATSTRINGHASH("super"), "1.48 Diamond Casino & Resort"},
		{"kuruma", "karin", ATSTRINGHASH("sport"), "1.21 Heists DLC"},
		{"kuruma2", "karin", ATSTRINGHASH("sport"), "1.21 Heists DLC"},
		{"l35", "declasse", ATSTRINGHASH("off_road"), "1.67 San Andreas Mercenaries"},
		{"l352", "declasse", ATSTRINGHASH("off_road"), "1.71 Money Fronts"},
		{"landstalker", "dundrear", ATSTRINGHASH("suv"), "1.01 Game Launch"},
		{"landstalker2", "dundrear", ATSTRINGHASH("suv"), "1.51 LS Summer Special"},
		{"laufer", "benefactor", ATSTRINGHASH("van"), "1.73 The Kortz Center Heist"},
		{"lazer", "", ATSTRINGHASH("plane"), "1.01 Game Launch"},
		{"le7b", "annis", ATSTRINGHASH("super"), "1.35 Cunning Stunts"},
		{"lectro", "principl", ATSTRINGHASH("motorcycle"), "1.21 Heists DLC"},
		{"lguard", "declasse", ATSTRINGHASH("emergency"), "1.01 Game Launch"},
		{"limo2", "benefac", ATSTRINGHASH("sedan"), "1.31 Executives and Other Criminals"},
		{"lm87", "benefac", ATSTRINGHASH("super"), "1.61 The Criminal Enterprises"},
		{"locust", "ocelot", ATSTRINGHASH("sport"), "1.48 Diamond Casino & Resort"},
		{"longfin", "shitzu", ATSTRINGHASH("boat"), "1.52 Cayo Perico Heist"},
		{"lrcgt", "benefactor", ATSTRINGHASH("super"), "1.73 The Kortz Center Heist"},
		{"luiva", "progen", ATSTRINGHASH("super"), "1.72 A Safehouse in the Hills"},
		{"lurcher", "albany", ATSTRINGHASH("muscle"), "1.30.1 Halloween Surprise"},
		{"luxor", "bucking", ATSTRINGHASH("plane"), "1.01 Game Launch"},
		{"luxor2", "bucking", ATSTRINGHASH("plane"), "1.27 Ill-Gotten Gains Part 1"},
		{"lynx", "ocelot", ATSTRINGHASH("sport"), "1.35 Cunning Stunts"},
		{"mamba", "declasse", ATSTRINGHASH("sport_classic"), "1.31 Executives and Other Criminals"},
		{"mammatus", "", ATSTRINGHASH("plane"), "1.01 Game Launch"},
		{"manana", "albany", ATSTRINGHASH("sport_classic"), "1.01 Game Launch"},
		{"manana2", "albany", ATSTRINGHASH("muscle"), "1.51 LS Summer Special"},
		{"manchez", "maibatsu", ATSTRINGHASH("motorcycle"), "1.36 Bikers"},
		{"manchez2", "maibatsu", ATSTRINGHASH("motorcycle"), "1.52 Cayo Perico Heist"},
		{"manchez3", "maibatsu", ATSTRINGHASH("motorcycle"), "1.64 Drug Wars"},
		{"marquis", "dinka", ATSTRINGHASH("boat"), "1.01 Game Launch"},
		{"marshall", "cheval", ATSTRINGHASH("off_road"), "1.18 Next Gen Release"},
		{"massacro", "dewbauch", ATSTRINGHASH("sport"), "1.13 High Life"},
		{"massacro2", "dewbauch", ATSTRINGHASH("sport"), "1.19 Festive Surprise 2014"},
		{"maverick", "", ATSTRINGHASH("helicopter"), "1.01 Game Launch"},
		{"maverick2", "", ATSTRINGHASH("helicopter"), "1.71 Money Fronts"},
		{"menacer", "hvy", ATSTRINGHASH("off_road"), "1.44 After Hours"},
		{"merula", "albany", ATSTRINGHASH("sedan"), "1.73 The Kortz Center Heist"},
		{"mesa", "canis", ATSTRINGHASH("suv"), "1.01 Game Launch"},
		{"mesa2", "canis", ATSTRINGHASH("suv"), "1.01 Game Launch"},
		{"mesa3", "canis", ATSTRINGHASH("off_road"), "1.01 Game Launch"},
		{"metrotrain", "", ATSTRINGHASH("rail"), "1.01 Game Launch"},
		{"michelli", "lampada", ATSTRINGHASH("sport_classic"), "1.43 Southern SA Super Sport Series"},
		{"microlight", "nagasaki", ATSTRINGHASH("plane"), "1.41 Smuggler's Run"},
		{"miljet", "bucking", ATSTRINGHASH("plane"), "1.16 SA Flight School"},
		{"minimus", "annis", ATSTRINGHASH("sedan"), "1.71 Money Fronts"},
		{"minitank", "", ATSTRINGHASH("military"), "1.49 Diamond Casino Heist"},
		{"minivan", "vapid", ATSTRINGHASH("van"), "1.01 Game Launch"},
		{"minivan2", "vapid", ATSTRINGHASH("van"), "1.33 Lowriders: Custom Classics"},
		{"mixer", "hvy", ATSTRINGHASH("industrial"), "1.01 Game Launch"},
		{"mixer2", "hvy", ATSTRINGHASH("industrial"), "1.01 Game Launch"},
		{"mogul", "mammoth", ATSTRINGHASH("plane"), "1.41 Smuggler's Run"},
		{"molotok", "", ATSTRINGHASH("plane"), "1.41 Smuggler's Run"},
		{"monroe", "pegassi", ATSTRINGHASH("sport_classic"), "1.01 Game Launch"},
		{"monster", "vapid", ATSTRINGHASH("off_road"), "1.15 Independence Day"},
		{"monster3", "bravado", ATSTRINGHASH("off_road"), "1.46 Arena War"},
		{"monster4", "bravado", ATSTRINGHASH("off_road"), "1.46 Arena War"},
		{"monster5", "bravado", ATSTRINGHASH("off_road"), "1.46 Arena War"},
		{"monstrociti", "maibatsu", ATSTRINGHASH("off_road"), "1.67 San Andreas Mercenaries"},
		{"moonbeam", "declasse", ATSTRINGHASH("muscle"), "1.30 Lowriders"},
		{"moonbeam2", "declasse", ATSTRINGHASH("muscle"), "1.30 Lowriders"},
		{"mower", "", ATSTRINGHASH("utility"), "1.01 Game Launch"},
		{"mule", "maibatsu", ATSTRINGHASH("commercial"), "1.01 Game Launch"},
		{"mule2", "maibatsu", ATSTRINGHASH("commercial"), "1.01 Game Launch"},
		{"mule3", "maibatsu", ATSTRINGHASH("commercial"), "1.21 Heists DLC"},
		{"mule4", "maibatsu", ATSTRINGHASH("commercial"), "1.44 After Hours"},
		{"mule5", "maibatsu", ATSTRINGHASH("commercial"), "1.58 The Contract"},
		{"nebula", "vulcar", ATSTRINGHASH("sport_classic"), "1.48 Diamond Casino & Resort"},
		{"nemesis", "principl", ATSTRINGHASH("motorcycle"), "1.01 Game Launch"},
		{"neo", "vysser", ATSTRINGHASH("sport"), "1.48 Diamond Casino & Resort"},
		{"neon", "pfister", ATSTRINGHASH("sport"), "1.42 The Doomsday Heist"},
		{"nero", "truffade", ATSTRINGHASH("super"), "1.37 Import/Export"},
		{"nero2", "truffade", ATSTRINGHASH("super"), "1.37 Import/Export"},
		{"nightblade", "western", ATSTRINGHASH("motorcycle"), "1.36 Bikers"},
		{"nightshade", "imponte", ATSTRINGHASH("muscle"), "1.31 Executives and Other Criminals"},
		{"nightshark", "hvy", ATSTRINGHASH("off_road"), "1.40 Gunrunning Pack"},
		{"nimbus", "bucking", ATSTRINGHASH("plane"), "1.34 Further Adventures in Finance and Felony"},
		{"ninef", "obey", ATSTRINGHASH("sport"), "1.01 Game Launch"},
		{"ninef2", "obey", ATSTRINGHASH("sport"), "1.01 Game Launch"},
		{"niobe", "ubermacht", ATSTRINGHASH("sport"), "1.69 Bottom Dollar Bounties"},
		{"nokota", "", ATSTRINGHASH("plane"), "1.41 Smuggler's Run"},
		{"novak", "lampadati", ATSTRINGHASH("suv"), "1.48 Diamond Casino & Resort"},
		{"omnis", "obey", ATSTRINGHASH("sport"), "1.35 Cunning Stunts"},
		{"omnisegt", "obey", ATSTRINGHASH("sport"), "1.61 The Criminal Enterprises"},
		{"openwheel1", "benefac", ATSTRINGHASH("open_wheel"), "1.51 LS Summer Special"},
		{"openwheel2", "declasse", ATSTRINGHASH("open_wheel"), "1.51 LS Summer Special"},
		{"oppressor", "pegassi", ATSTRINGHASH("motorcycle"), "1.40 Gunrunning Pack"},
		{"oppressor2", "pegassi", ATSTRINGHASH("motorcycle"), "1.44 After Hours"},
		{"oracle", "ubermach", ATSTRINGHASH("coupe"), "1.01 Game Launch"},
		{"oracle2", "ubermach", ATSTRINGHASH("coupe"), "1.01 Game Launch"},
		{"osiris", "pegassi", ATSTRINGHASH("super"), "1.27 Ill-Gotten Gains Part 1"},
		{"outlaw", "nagasaki", ATSTRINGHASH("off_road"), "1.49 Diamond Casino Heist"},
		{"packer", "mtl", ATSTRINGHASH("commercial"), "1.01 Game Launch"},
		{"panthere", "toundra", ATSTRINGHASH("sport"), "1.64 Drug Wars"},
		{"panto", "benefac", ATSTRINGHASH("compacts"), "1.14 I'm Not a Hipster"},
		{"paradise", "bravado", ATSTRINGHASH("van"), "1.06 Beach Bum"},
		{"paragon", "enus", ATSTRINGHASH("sport"), "1.48 Diamond Casino & Resort"},
		{"paragon2", "enus", ATSTRINGHASH("sport"), "1.48 Diamond Casino & Resort"},
		{"paragon3", "enus", ATSTRINGHASH("sport"), "1.69 Bottom Dollar Bounties"},
		{"pariah", "ocelot", ATSTRINGHASH("sport"), "1.42 The Doomsday Heist"},
		{"patriot", "mammoth", ATSTRINGHASH("suv"), "1.01 Game Launch"},
		{"patriot2", "mammoth", ATSTRINGHASH("suv"), "1.44 After Hours"},
		{"patriot3", "mammoth", ATSTRINGHASH("off_road"), "1.58 The Contract"},
		{"patrolboat", "", ATSTRINGHASH("boat"), "1.52 Cayo Perico Heist"},
		{"pbus", "", ATSTRINGHASH("emergency"), "1.01 Game Launch"},
		{"pbus2", "", ATSTRINGHASH("service"), "1.44 After Hours"},
		{"pcj", "shitzu", ATSTRINGHASH("motorcycle"), "1.01 Game Launch"},
		{"penetrator", "ocelot", ATSTRINGHASH("super"), "1.37 Import/Export"},
		{"penumbra", "maibatsu", ATSTRINGHASH("sport"), "1.01 Game Launch"},
		{"penumbra2", "maibatsu", ATSTRINGHASH("sport"), "1.51 LS Summer Special"},
		{"peyote", "vapid", ATSTRINGHASH("sport_classic"), "1.01 Game Launch"},
		{"peyote2", "vapid", ATSTRINGHASH("muscle"), "1.48 Diamond Casino & Resort"},
		{"peyote3", "vapid", ATSTRINGHASH("sport_classic"), "1.51 LS Summer Special"},
		{"pfister811", "pfister", ATSTRINGHASH("super"), "1.34 Further Adventures in Finance and Felony"},
		{"phantom", "jobuilt", ATSTRINGHASH("commercial"), "1.01 Game Launch"},
		{"phantom2", "jobuilt", ATSTRINGHASH("commercial"), "1.37 Import/Export"},
		{"phantom3", "jobuilt", ATSTRINGHASH("commercial"), "1.40 Gunrunning Pack"},
		{"phantom4", "jobuilt", ATSTRINGHASH("commercial"), "1.68 The Chop Shop"},
		{"phoenix", "imponte", ATSTRINGHASH("muscle"), "1.01 Game Launch"},
		{"picador", "cheval", ATSTRINGHASH("muscle"), "1.01 Game Launch"},
		{"pigalle", "lampada", ATSTRINGHASH("sport_classic"), "1.14 I'm Not a Hipster"},
		{"pipistrello", "overflod", ATSTRINGHASH("super"), "1.69 Bottom Dollar Bounties"},
		{"pizzaboy", "pegassi", ATSTRINGHASH("motorcycle"), "1.69 Bottom Dollar Bounties"},
		{"polbuffalo", "bravado", ATSTRINGHASH("emergency"), "1.72 A Safehouse in the Hills"},
		{"polbuffalo6", "bravado", ATSTRINGHASH("emergency"), "1.72 A Safehouse in the Hills"},
		{"polcaracara", "vapid", ATSTRINGHASH("emergency"), "1.70 Agents of Sabotage"},
		{"polcoquette4", "inverto", ATSTRINGHASH("emergency"), "1.70 Agents of Sabotage"},
		{"poldominator10", "vapid", ATSTRINGHASH("emergency"), "1.69 Bottom Dollar Bounties"},
		{"poldorado", "bravado", ATSTRINGHASH("emergency"), "1.69 Bottom Dollar Bounties"},
		{"polfaction2", "willard", ATSTRINGHASH("emergency"), "1.70 Agents of Sabotage"},
		{"polgauntlet", "bravado", ATSTRINGHASH("emergency"), "1.68 The Chop Shop"},
		{"polgreenwood", "bravado", ATSTRINGHASH("emergency"), "1.69 Bottom Dollar Bounties"},
		{"police", "", ATSTRINGHASH("emergency"), "1.01 Game Launch"},
		{"police2", "", ATSTRINGHASH("emergency"), "1.01 Game Launch"},
		{"police3", "", ATSTRINGHASH("emergency"), "1.01 Game Launch"},
		{"police4", "vapid", ATSTRINGHASH("emergency"), "1.01 Game Launch"},
		{"police5", "vapid", ATSTRINGHASH("emergency"), "1.68 The Chop Shop"},
		{"policeb", "", ATSTRINGHASH("emergency"), "1.01 Game Launch"},
		{"policeb2", "western", ATSTRINGHASH("emergency"), "1.71 Money Fronts"},
		{"policeold1", "", ATSTRINGHASH("emergency"), "1.01 Game Launch"},
		{"policeold2", "", ATSTRINGHASH("emergency"), "1.01 Game Launch"},
		{"policet", "", ATSTRINGHASH("emergency"), "1.01 Game Launch"},
		{"policet3", "", ATSTRINGHASH("emergency"), "1.69 Bottom Dollar Bounties"},
		{"polignus", "pegassi", ATSTRINGHASH("emergency"), "1.73 The Kortz Center Heist"},
		{"polimpaler5", "declasse", ATSTRINGHASH("emergency"), "1.69 Bottom Dollar Bounties"},
		{"polimpaler6", "declasse", ATSTRINGHASH("emergency"), "1.69 Bottom Dollar Bounties"},
		{"polmav", "", ATSTRINGHASH("helicopter"), "1.01 Game Launch"},
		{"polterminus", "canis", ATSTRINGHASH("emergency"), "1.70 Agents of Sabotage"},
		{"pony", "brute", ATSTRINGHASH("van"), "1.01 Game Launch"},
		{"pony2", "brute", ATSTRINGHASH("van"), "1.01 Game Launch"},
		{"postlude", "dinka", ATSTRINGHASH("coupe"), "1.61 The Criminal Enterprises"},
		{"pounder", "mtl", ATSTRINGHASH("commercial"), "1.01 Game Launch"},
		{"pounder2", "mtl", ATSTRINGHASH("commercial"), "1.44 After Hours"},
		{"powersurge", "western", ATSTRINGHASH("motorcycle"), "1.64 Drug Wars"},
		{"prairie", "bollokan", ATSTRINGHASH("compacts"), "1.01 Game Launch"},
		{"pranger", "declasse", ATSTRINGHASH("emergency"), "1.01 Game Launch"},
		{"predator", "", ATSTRINGHASH("boat"), "1.01 Game Launch"},
		{"premier", "declasse", ATSTRINGHASH("sedan"), "1.01 Game Launch"},
		{"previon", "karin", ATSTRINGHASH("coupe"), "1.57 LS Tuners"},
		{"primo", "albany", ATSTRINGHASH("sedan"), "1.01 Game Launch"},
		{"primo2", "albany", ATSTRINGHASH("sedan"), "1.30 Lowriders"},
		{"proptrailer", "", ATSTRINGHASH("utility"), "1.01 Game Launch"},
		{"prototipo", "grotti", ATSTRINGHASH("super"), "1.34 Further Adventures in Finance and Felony"},
		{"pyro", "bucking", ATSTRINGHASH("plane"), "1.41 Smuggler's Run"},
		{"r300", "annis", ATSTRINGHASH("sport"), "1.64 Drug Wars"},
		{"radi", "vapid", ATSTRINGHASH("suv"), "1.01 Game Launch"},
		{"raiden", "coil", ATSTRINGHASH("sport"), "1.42 The Doomsday Heist"},
		{"raiju", "", ATSTRINGHASH("plane"), "1.67 San Andreas Mercenaries"},
		{"raketrailer", "", ATSTRINGHASH("utility"), "1.01 Game Launch"},
		{"rallytruck", "mtl", ATSTRINGHASH("service"), "1.35 Cunning Stunts"},
		{"rancherxl", "declasse", ATSTRINGHASH("off_road"), "1.01 Game Launch"},
		{"rancherxl2", "declasse", ATSTRINGHASH("off_road"), "1.01 Game Launch"},
		{"rapidgt", "dewbauch", ATSTRINGHASH("sport"), "1.01 Game Launch"},
		{"rapidgt2", "dewbauch", ATSTRINGHASH("sport"), "1.01 Game Launch"},
		{"rapidgt3", "dewbauch", ATSTRINGHASH("sport_classic"), "1.41 Smuggler's Run"},
		{"rapidgt4", "dewbauch", ATSTRINGHASH("sport"), "1.71 Money Fronts"},
		{"raptor", "bf", ATSTRINGHASH("sport"), "1.36 Bikers"},
		{"ratbike", "western", ATSTRINGHASH("motorcycle"), "1.36 Bikers"},
		{"ratel", "vapid", ATSTRINGHASH("off_road"), "1.67 San Andreas Mercenaries"},
		{"ratloader", "", ATSTRINGHASH("muscle"), "1.01 Game Launch"},
		{"ratloader2", "bravado", ATSTRINGHASH("muscle"), "1.19 Festive Surprise 2014"},
		{"rcbandito", "", ATSTRINGHASH("off_road"), "1.46 Arena War"},
		{"reaper", "pegassi", ATSTRINGHASH("super"), "1.34 Further Adventures in Finance and Felony"},
		{"rebel", "karin", ATSTRINGHASH("off_road"), "1.01 Game Launch"},
		{"rebel2", "karin", ATSTRINGHASH("off_road"), "1.01 Game Launch"},
		{"rebla", "ubermacht", ATSTRINGHASH("suv"), "1.49 Diamond Casino Heist"},
		{"reever", "western", ATSTRINGHASH("motorcycle"), "1.58 The Contract"},
		{"regina", "dundrear", ATSTRINGHASH("sedan"), "1.01 Game Launch"},
		{"remus", "annis", ATSTRINGHASH("sport"), "1.57 LS Tuners"},
		{"rentalbus", "", ATSTRINGHASH("service"), "1.01 Game Launch"},
		{"retinue", "vapid", ATSTRINGHASH("sport_classic"), "1.41 Smuggler's Run"},
		{"retinue2", "vapid", ATSTRINGHASH("sport_classic"), "1.49 Diamond Casino Heist"},
		{"revolter", "ubermach", ATSTRINGHASH("sport"), "1.42 The Doomsday Heist"},
		{"rhapsody", "declasse", ATSTRINGHASH("compacts"), "1.14 I'm Not a Hipster"},
		{"rhinehart", "ubermacht", ATSTRINGHASH("sedan"), "1.61 The Criminal Enterprises"},
		{"rhino", "", ATSTRINGHASH("military"), "1.01 Game Launch"},
		{"riata", "vapid", ATSTRINGHASH("off_road"), "1.42 The Doomsday Heist"},
		{"riot", "", ATSTRINGHASH("emergency"), "1.01 Game Launch"},
		{"riot2", "", ATSTRINGHASH("emergency"), "1.42 The Doomsday Heist"},
		{"ripley", "", ATSTRINGHASH("utility"), "1.01 Game Launch"},
		{"rocoto", "obey", ATSTRINGHASH("suv"), "1.01 Game Launch"},
		{"rogue", "western", ATSTRINGHASH("plane"), "1.41 Smuggler's Run"},
		{"romero", "chariot", ATSTRINGHASH("sedan"), "1.01 Game Launch"},
		{"rrocket", "western", ATSTRINGHASH("motorcycle"), "1.48 Diamond Casino & Resort"},
		{"rt3000", "dinka", ATSTRINGHASH("sport"), "1.57 LS Tuners"},
		{"rubble", "jobuilt", ATSTRINGHASH("industrial"), "1.01 Game Launch"},
		{"ruffian", "pegassi", ATSTRINGHASH("motorcycle"), "1.01 Game Launch"},
		{"ruiner", "imponte", ATSTRINGHASH("muscle"), "1.01 Game Launch"},
		{"ruiner2", "imponte", ATSTRINGHASH("muscle"), "1.37 Import/Export"},
		{"ruiner3", "imponte", ATSTRINGHASH("muscle"), "1.37 Import/Export"},
		{"ruiner4", "imponte", ATSTRINGHASH("muscle"), "1.61 The Criminal Enterprises"},
		{"rumpo", "bravado", ATSTRINGHASH("van"), "1.01 Game Launch"},
		{"rumpo2", "bravado", ATSTRINGHASH("van"), "1.01 Game Launch"},
		{"rumpo3", "bravado", ATSTRINGHASH("van"), "1.34 Further Adventures in Finance and Felony"},
		{"ruston", "hijak", ATSTRINGHASH("sport"), "1.38 Special Vehicle Circuit"},
		{"s80", "annis", ATSTRINGHASH("super"), "1.48 Diamond Casino & Resort"},
		{"sabregt", "declasse", ATSTRINGHASH("muscle"), "1.01 Game Launch"},
		{"sabregt2", "declasse", ATSTRINGHASH("muscle"), "1.33 Lowriders: Custom Classics"},
		{"sadler", "vapid", ATSTRINGHASH("utility"), "1.01 Game Launch"},
		{"sadler2", "vapid", ATSTRINGHASH("utility"), "1.01 Game Launch"},
		{"sanchez", "maibatsu", ATSTRINGHASH("motorcycle"), "1.01 Game Launch"},
		{"sanchez2", "maibatsu", ATSTRINGHASH("motorcycle"), "1.01 Game Launch"},
		{"sanctus", "lcc", ATSTRINGHASH("motorcycle"), "1.36 Bikers"},
		{"sandking", "vapid", ATSTRINGHASH("off_road"), "1.01 Game Launch"},
		{"sandking2", "vapid", ATSTRINGHASH("off_road"), "1.01 Game Launch"},
		{"savage", "", ATSTRINGHASH("helicopter"), "1.21 Heists DLC"},
		{"savestra", "annis", ATSTRINGHASH("sport_classic"), "1.42 The Doomsday Heist"},
		{"sc1", "ubermach", ATSTRINGHASH("super"), "1.42 The Doomsday Heist"},
		{"scarab", "hvy", ATSTRINGHASH("military"), "1.46 Arena War"},
		{"scarab2", "hvy", ATSTRINGHASH("military"), "1.46 Arena War"},
		{"scarab3", "hvy", ATSTRINGHASH("military"), "1.46 Arena War"},
		{"schafter2", "benefac", ATSTRINGHASH("sedan"), "1.01 Game Launch"},
		{"schafter3", "benefac", ATSTRINGHASH("sport"), "1.31 Executives and Other Criminals"},
		{"schafter4", "benefac", ATSTRINGHASH("sport"), "1.31 Executives and Other Criminals"},
		{"schafter5", "benefac", ATSTRINGHASH("sedan"), "1.31 Executives and Other Criminals"},
		{"schafter6", "benefac", ATSTRINGHASH("sedan"), "1.31 Executives and Other Criminals"},
		{"schlagen", "benefactor", ATSTRINGHASH("sport"), "1.46 Arena War"},
		{"schwarzer", "benefac", ATSTRINGHASH("sport"), "1.01 Game Launch"},
		{"scorcher", "", ATSTRINGHASH("cycle"), "1.01 Game Launch"},
		{"scramjet", "declasse", ATSTRINGHASH("super"), "1.44 After Hours"},
		{"scrap", "", ATSTRINGHASH("utility"), "1.01 Game Launch"},
		{"seabreeze", "western", ATSTRINGHASH("plane"), "1.41 Smuggler's Run"},
		{"seashark", "speedoph", ATSTRINGHASH("boat"), "1.01 Game Launch"},
		{"seashark2", "speedoph", ATSTRINGHASH("boat"), "1.01 Game Launch"},
		{"seashark3", "speedoph", ATSTRINGHASH("boat"), "1.31 Executives and Other Criminals"},
		{"seasparrow", "", ATSTRINGHASH("helicopter"), "1.43 Southern SA Super Sport Series"},
		{"seasparrow2", "", ATSTRINGHASH("helicopter"), "1.52 Cayo Perico Heist"},
		{"seasparrow3", "", ATSTRINGHASH("helicopter"), "1.52 Cayo Perico Heist"},
		{"seminole", "canis", ATSTRINGHASH("suv"), "1.01 Game Launch"},
		{"seminole2", "canis", ATSTRINGHASH("suv"), "1.51 LS Summer Special"},
		{"sentinel", "ubermach", ATSTRINGHASH("coupe"), "1.01 Game Launch"},
		{"sentinel2", "ubermach", ATSTRINGHASH("coupe"), "1.01 Game Launch"},
		{"sentinel3", "ubermach", ATSTRINGHASH("sport"), "1.42 The Doomsday Heist"},
		{"sentinel4", "ubermach", ATSTRINGHASH("sport"), "1.61 The Criminal Enterprises"},
		{"sentinel5", "ubermacht", ATSTRINGHASH("sport"), "1.71 Money Fronts"},
		{"sentinel6", "ubermacht", ATSTRINGHASH("sedan"), "1.72 A Safehouse in the Hills"},
		{"serrano", "benefac", ATSTRINGHASH("suv"), "1.01 Game Launch"},
		{"seven70", "dewbauch", ATSTRINGHASH("sport"), "1.34 Further Adventures in Finance and Felony"},
		{"shamal", "bucking", ATSTRINGHASH("plane"), "1.01 Game Launch"},
		{"sheava", "emperor", ATSTRINGHASH("super"), "1.35 Cunning Stunts"},
		{"sheriff", "", ATSTRINGHASH("emergency"), "1.01 Game Launch"},
		{"sheriff2", "", ATSTRINGHASH("emergency"), "1.01 Game Launch"},
		{"shinobi", "nagasaki", ATSTRINGHASH("motorcycle"), "1.58 The Contract"},
		{"shotaro", "nagasaki", ATSTRINGHASH("motorcycle"), "1.36 Bikers"},
		{"skylift", "", ATSTRINGHASH("helicopter"), "1.01 Game Launch"},
		{"slamtruck", "vapid", ATSTRINGHASH("utility"), "1.52 Cayo Perico Heist"},
		{"slamvan", "vapid", ATSTRINGHASH("muscle"), "1.19 Festive Surprise 2014"},
		{"slamvan2", "vapid", ATSTRINGHASH("muscle"), "1.21 Heists DLC"},
		{"slamvan3", "vapid", ATSTRINGHASH("muscle"), "1.33 Lowriders: Custom Classics"},
		{"slamvan4", "vapid", ATSTRINGHASH("muscle"), "1.46 Arena War"},
		{"slamvan5", "vapid", ATSTRINGHASH("muscle"), "1.46 Arena War"},
		{"slamvan6", "vapid", ATSTRINGHASH("muscle"), "1.46 Arena War"},
		{"sm722", "benefac", ATSTRINGHASH("sport"), "1.61 The Criminal Enterprises"},
		{"sovereign", "western", ATSTRINGHASH("motorcycle"), "1.15 Independence Day"},
		{"specter", "dewbauch", ATSTRINGHASH("sport"), "1.37 Import/Export"},
		{"specter2", "dewbauch", ATSTRINGHASH("sport"), "1.37 Import/Export"},
		{"speeder", "pegassi", ATSTRINGHASH("boat"), "1.06 Beach Bum"},
		{"speeder2", "pegassi", ATSTRINGHASH("boat"), "1.31 Executives and Other Criminals"},
		{"speedo", "vapid", ATSTRINGHASH("van"), "1.01 Game Launch"},
		{"speedo2", "vapid", ATSTRINGHASH("van"), "1.01 Game Launch"},
		{"speedo4", "vapid", ATSTRINGHASH("van"), "1.44 After Hours"},
		{"speedo5", "vapid", ATSTRINGHASH("van"), "1.67 San Andreas Mercenaries"},
		{"squaddie", "mammoth", ATSTRINGHASH("suv"), "1.52 Cayo Perico Heist"},
		{"squalo", "shitzu", ATSTRINGHASH("boat"), "1.01 Game Launch"},
		{"stafford", "enus", ATSTRINGHASH("sedan"), "1.44 After Hours"},
		{"stalion", "declasse", ATSTRINGHASH("muscle"), "1.18 Next Gen Release"},
		{"stalion2", "declasse", ATSTRINGHASH("muscle"), "1.18 Next Gen Release"},
		{"stanier", "vapid", ATSTRINGHASH("sedan"), "1.01 Game Launch"},
		{"starling", "", ATSTRINGHASH("plane"), "1.41 Smuggler's Run"},
		{"stinger", "grotti", ATSTRINGHASH("sport_classic"), "1.01 Game Launch"},
		{"stingergt", "grotti", ATSTRINGHASH("sport_classic"), "1.01 Game Launch"},
		{"stingertt", "grotti", ATSTRINGHASH("sport"), "1.67 San Andreas Mercenaries"},
		{"stockade", "brute", ATSTRINGHASH("commercial"), "1.01 Game Launch"},
		{"stockade3", "brute", ATSTRINGHASH("commercial"), "1.01 Game Launch"},
		{"stockade4", "brute", ATSTRINGHASH("commercial"), "1.71 Money Fronts"},
		{"stratum", "zirconiu", ATSTRINGHASH("sedan"), "1.01 Game Launch"},
		{"streamer216", "mammoth", ATSTRINGHASH("plane"), "1.67 San Andreas Mercenaries"},
		{"streiter", "benefactor", ATSTRINGHASH("sport"), "1.42 The Doomsday Heist"},
		{"stretch", "dundrear", ATSTRINGHASH("sedan"), "1.01 Game Launch"},
		{"strikeforce", "", ATSTRINGHASH("plane"), "1.44 After Hours"},
		{"stromberg", "ocelot", ATSTRINGHASH("sport_classic"), "1.42 The Doomsday Heist"},
		{"stryder", "nagasaki", ATSTRINGHASH("motorcycle"), "1.49 Diamond Casino Heist"},
		{"stunt", "", ATSTRINGHASH("plane"), "1.01 Game Launch"},
		{"submersible", "", ATSTRINGHASH("boat"), "1.01 Game Launch"},
		{"submersible2", "", ATSTRINGHASH("boat"), "1.18 Next Gen Release"},
		{"sugoi", "dinka", ATSTRINGHASH("sport"), "1.49 Diamond Casino Heist"},
		{"sultan", "karin", ATSTRINGHASH("sport"), "1.01 Game Launch"},
		{"sultan2", "karin", ATSTRINGHASH("sport"), "1.49 Diamond Casino Heist"},
		{"sultan3", "karin", ATSTRINGHASH("sport"), "1.57 LS Tuners"},
		{"sultanrs", "karin", ATSTRINGHASH("super"), "1.32 January 2016"},
		{"suntrap", "shitzu", ATSTRINGHASH("boat"), "1.01 Game Launch"},
		{"superd", "enus", ATSTRINGHASH("sedan"), "1.01 Game Launch"},
		{"supervolito", "bucking", ATSTRINGHASH("helicopter"), "1.31 Executives and Other Criminals"},
		{"supervolito2", "bucking", ATSTRINGHASH("helicopter"), "1.31 Executives and Other Criminals"},
		{"surano", "benefac", ATSTRINGHASH("sport"), "1.01 Game Launch"},
		{"surfer", "bf", ATSTRINGHASH("van"), "1.01 Game Launch"},
		{"surfer2", "bf", ATSTRINGHASH("van"), "1.01 Game Launch"},
		{"surfer3", "bf", ATSTRINGHASH("van"), "1.64 Drug Wars"},
		{"surge", "cheval", ATSTRINGHASH("sedan"), "1.01 Game Launch"},
		{"suzume", "overflod", ATSTRINGHASH("super"), "1.71 Money Fronts"},
		{"swift", "bucking", ATSTRINGHASH("helicopter"), "1.16 SA Flight School"},
		{"swift2", "bucking", ATSTRINGHASH("helicopter"), "1.27 Ill-Gotten Gains Part 1"},
		{"swinger", "ocelot", ATSTRINGHASH("sport_classic"), "1.44 After Hours"},
		{"t20", "progen", ATSTRINGHASH("super"), "1.28 Ill-Gotten Gains Part 2"},
		{"taco", "", ATSTRINGHASH("van"), "1.01 Game Launch"},
		{"tahoma", "declasse", ATSTRINGHASH("muscle"), "1.64 Drug Wars"},
		{"tailgater", "obey", ATSTRINGHASH("sedan"), "1.01 Game Launch"},
		{"tailgater2", "obey", ATSTRINGHASH("sedan"), "1.57 LS Tuners"},
		{"taipan", "cheval", ATSTRINGHASH("super"), "1.43 Southern SA Super Sport Series"},
		{"tampa", "declasse", ATSTRINGHASH("muscle"), "1.31.1 Festive Surprise 2015"},
		{"tampa2", "declasse", ATSTRINGHASH("sport"), "1.35 Cunning Stunts"},
		{"tampa3", "declasse", ATSTRINGHASH("muscle"), "1.40 Gunrunning Pack"},
		{"tampa4", "declasse", ATSTRINGHASH("muscle"), "1.71 Money Fronts"},
		{"tanker", "", ATSTRINGHASH("utility"), "1.01 Game Launch"},
		{"tanker2", "", ATSTRINGHASH("utility"), "1.21 Heists DLC"},
		{"tankercar", "", ATSTRINGHASH("rail"), "1.01 Game Launch"},
		{"taxi", "", ATSTRINGHASH("service"), "1.01 Game Launch"},
		{"technical", "karin", ATSTRINGHASH("off_road"), "1.21 Heists DLC"},
		{"technical2", "karin", ATSTRINGHASH("off_road"), "1.37 Import/Export"},
		{"technical3", "karin", ATSTRINGHASH("off_road"), "1.40 Gunrunning Pack"},
		{"tempesta", "pegassi", ATSTRINGHASH("super"), "1.37 Import/Export"},
		{"tenf", "obey", ATSTRINGHASH("sport"), "1.61 The Criminal Enterprises"},
		{"tenf2", "obey", ATSTRINGHASH("sport"), "1.61 The Criminal Enterprises"},
		{"terbyte", "benefactor", ATSTRINGHASH("commercial"), "1.44 After Hours"},
		{"terminus", "canis", ATSTRINGHASH("off_road"), "1.68 The Chop Shop"},
		{"tezeract", "pegassi", ATSTRINGHASH("super"), "1.43 Southern SA Super Sport Series"},
		{"thrax", "truffade", ATSTRINGHASH("super"), "1.48 Diamond Casino & Resort"},
		{"thrust", "dinka", ATSTRINGHASH("motorcycle"), "1.13 High Life"},
		{"thruster", "mammoth", ATSTRINGHASH("military"), "1.42 The Doomsday Heist"},
		{"tigon", "lampadati", ATSTRINGHASH("super"), "1.51 LS Summer Special"},
		{"tiptruck", "brute", ATSTRINGHASH("industrial"), "1.01 Game Launch"},
		{"tiptruck2", "", ATSTRINGHASH("industrial"), "1.01 Game Launch"},
		{"titan", "", ATSTRINGHASH("plane"), "1.01 Game Launch"},
		{"titan2", "eberhard", ATSTRINGHASH("plane"), "1.70 Agents of Sabotage"},
		{"toreador", "pegassi", ATSTRINGHASH("sport_classic"), "1.52 Cayo Perico Heist"},
		{"torero", "pegassi", ATSTRINGHASH("sport_classic"), "1.40 Gunrunning Pack"},
		{"torero2", "pegassi", ATSTRINGHASH("super"), "1.61 The Criminal Enterprises"},
		{"tornado", "declasse", ATSTRINGHASH("sport_classic"), "1.01 Game Launch"},
		{"tornado2", "declasse", ATSTRINGHASH("sport_classic"), "1.01 Game Launch"},
		{"tornado3", "declasse", ATSTRINGHASH("sport_classic"), "1.01 Game Launch"},
		{"tornado4", "declasse", ATSTRINGHASH("sport_classic"), "1.01 Game Launch"},
		{"tornado5", "declasse", ATSTRINGHASH("sport_classic"), "1.33 Lowriders: Custom Classics"},
		{"tornado6", "declasse", ATSTRINGHASH("sport_classic"), "1.36 Bikers"},
		{"toro", "lampada", ATSTRINGHASH("boat"), "1.28 Ill-Gotten Gains Part 2"},
		{"toro2", "lampada", ATSTRINGHASH("boat"), "1.31 Executives and Other Criminals"},
		{"toros", "pegassi", ATSTRINGHASH("suv"), "1.46 Arena War"},
		{"tourbus", "", ATSTRINGHASH("service"), "1.01 Game Launch"},
		{"towtruck", "", ATSTRINGHASH("utility"), "1.01 Game Launch"},
		{"towtruck2", "", ATSTRINGHASH("utility"), "1.01 Game Launch"},
		{"towtruck3", "", ATSTRINGHASH("utility"), "1.68 The Chop Shop"},
		{"towtruck4", "", ATSTRINGHASH("utility"), "1.68 The Chop Shop"},
		{"tr2", "", ATSTRINGHASH("utility"), "1.01 Game Launch"},
		{"tr3", "", ATSTRINGHASH("utility"), "1.01 Game Launch"},
		{"tr4", "", ATSTRINGHASH("utility"), "1.01 Game Launch"},
		{"tractor", "", ATSTRINGHASH("utility"), "1.01 Game Launch"},
		{"tractor2", "stanley", ATSTRINGHASH("utility"), "1.01 Game Launch"},
		{"tractor3", "stanley", ATSTRINGHASH("utility"), "1.01 Game Launch"},
		{"trailerlarge", "", ATSTRINGHASH("utility"), "1.40 Gunrunning Pack"},
		{"trailerlogs", "", ATSTRINGHASH("utility"), "1.01 Game Launch"},
		{"trailers", "", ATSTRINGHASH("utility"), "1.01 Game Launch"},
		{"trailers2", "", ATSTRINGHASH("utility"), "1.01 Game Launch"},
		{"trailers3", "", ATSTRINGHASH("utility"), "1.01 Game Launch"},
		{"trailers4", "", ATSTRINGHASH("utility"), "1.40 Gunrunning Pack"},
		{"trailers5", "", ATSTRINGHASH("utility"), "1.68 The Chop Shop"},
		{"trailersmall", "", ATSTRINGHASH("utility"), "1.01 Game Launch"},
		{"trailersmall2", "vomfeuer", ATSTRINGHASH("military"), "1.40 Gunrunning Pack"},
		{"trash", "", ATSTRINGHASH("service"), "1.01 Game Launch"},
		{"trash2", "", ATSTRINGHASH("service"), "1.21 Heists DLC"},
		{"trflat", "", ATSTRINGHASH("utility"), "1.01 Game Launch"},
		{"trflat2", "", ATSTRINGHASH("utility"), "1.73 The Kortz Center Heist"},
		{"tribike", "", ATSTRINGHASH("cycle"), "1.01 Game Launch"},
		{"tribike2", "", ATSTRINGHASH("cycle"), "1.01 Game Launch"},
		{"tribike3", "", ATSTRINGHASH("cycle"), "1.01 Game Launch"},
		{"trophytruck", "vapid", ATSTRINGHASH("off_road"), "1.35 Cunning Stunts"},
		{"trophytruck2", "vapid", ATSTRINGHASH("off_road"), "1.35 Cunning Stunts"},
		{"tropic", "shitzu", ATSTRINGHASH("boat"), "1.01 Game Launch"},
		{"tropic2", "shitzu", ATSTRINGHASH("boat"), "1.31 Executives and Other Criminals"},
		{"tropos", "lampada", ATSTRINGHASH("sport"), "1.35 Cunning Stunts"},
		{"tug", "", ATSTRINGHASH("boat"), "1.34 Further Adventures in Finance and Felony"},
		{"tula", "mammoth", ATSTRINGHASH("plane"), "1.41 Smuggler's Run"},
		{"tulip", "declasse", ATSTRINGHASH("muscle"), "1.46 Arena War"},
		{"tulip2", "declasse", ATSTRINGHASH("muscle"), "1.64 Drug Wars"},
		{"turismo2", "grotti", ATSTRINGHASH("sport_classic"), "1.38 Special Vehicle Circuit"},
		{"turismo3", "grotti", ATSTRINGHASH("super"), "1.68 The Chop Shop"},
		{"turismor", "grotti", ATSTRINGHASH("super"), "1.11 Business"},
		{"tvtrailer", "", ATSTRINGHASH("utility"), "1.01 Game Launch"},
		{"tvtrailer2", "", ATSTRINGHASH("utility"), "1.68 The Chop Shop"},
		{"tyrant", "overflod", ATSTRINGHASH("super"), "1.43 Southern SA Super Sport Series"},
		{"tyrus", "progen", ATSTRINGHASH("super"), "1.35 Cunning Stunts"},
		{"uranus", "vapid", ATSTRINGHASH("sport_classic"), "1.70 Agents of Sabotage"},
		{"utillitruck", "", ATSTRINGHASH("utility"), "1.01 Game Launch"},
		{"utillitruck2", "", ATSTRINGHASH("utility"), "1.01 Game Launch"},
		{"utillitruck3", "", ATSTRINGHASH("utility"), "1.01 Game Launch"},
		{"vacca", "pegassi", ATSTRINGHASH("super"), "1.01 Game Launch"},
		{"vader", "shitzu", ATSTRINGHASH("motorcycle"), "1.01 Game Launch"},
		{"vagner", "dewbauch", ATSTRINGHASH("super"), "1.40 Gunrunning Pack"},
		{"vagrant", "maxwell", ATSTRINGHASH("off_road"), "1.49 Diamond Casino Heist"},
		{"valkyrie", "", ATSTRINGHASH("helicopter"), "1.21 Heists DLC"},
		{"valkyrie2", "", ATSTRINGHASH("helicopter"), "1.31 Executives and Other Criminals"},
		{"vamos", "declasse", ATSTRINGHASH("muscle"), "1.46 Arena War"},
		{"vectre", "emperor", ATSTRINGHASH("sport"), "1.57 LS Tuners"},
		{"velenogt", "grotti", ATSTRINGHASH("super"), "1.73 The Kortz Center Heist"},
		{"velum", "", ATSTRINGHASH("plane"), "1.01 Game Launch"},
		{"velum2", "", ATSTRINGHASH("plane"), "1.21 Heists DLC"},
		{"verlierer2", "bravado", ATSTRINGHASH("sport"), "1.31 Executives and Other Criminals"},
		{"verus", "dinka", ATSTRINGHASH("off_road"), "1.52 Cayo Perico Heist"},
		{"vestra", "bucking", ATSTRINGHASH("plane"), "1.11 Business"},
		{"vetir", "", ATSTRINGHASH("military"), "1.52 Cayo Perico Heist"},
		{"veto", "dinka", ATSTRINGHASH("sport"), "1.52 Cayo Perico Heist"},
		{"veto2", "dinka", ATSTRINGHASH("sport"), "1.52 Cayo Perico Heist"},
		{"vigero", "declasse", ATSTRINGHASH("muscle"), "1.01 Game Launch"},
		{"vigero2", "declasse", ATSTRINGHASH("muscle"), "1.61 The Criminal Enterprises"},
		{"vigero3", "declasse", ATSTRINGHASH("muscle"), "1.68 The Chop Shop"},
		{"vigilante", "", ATSTRINGHASH("super"), "1.41 Smuggler's Run"},
		{"vindicator", "dinka", ATSTRINGHASH("motorcycle"), "1.28 Ill-Gotten Gains Part 2"},
		{"virgo", "albany", ATSTRINGHASH("muscle"), "1.27 Ill-Gotten Gains Part 1"},
		{"virgo2", "dundrear", ATSTRINGHASH("muscle"), "1.33 Lowriders: Custom Classics"},
		{"virgo3", "dundrear", ATSTRINGHASH("muscle"), "1.33 Lowriders: Custom Classics"},
		{"virtue", "ocelot", ATSTRINGHASH("super"), "1.64 Drug Wars"},
		{"viseris", "lampadati", ATSTRINGHASH("sport_classic"), "1.42 The Doomsday Heist"},
		{"visione", "grotti", ATSTRINGHASH("super"), "1.41 Smuggler's Run"},
		{"vivanite", "karin", ATSTRINGHASH("suv"), "1.68 The Chop Shop"},
		{"vivanite2", "karin", ATSTRINGHASH("service"), "1.72 A Safehouse in the Hills"},
		{"volatol", "", ATSTRINGHASH("plane"), "1.42 The Doomsday Heist"},
		{"volatus", "bucking", ATSTRINGHASH("helicopter"), "1.34 Further Adventures in Finance and Felony"},
		{"voltic", "coil", ATSTRINGHASH("super"), "1.01 Game Launch"},
		{"voltic2", "coil", ATSTRINGHASH("super"), "1.37 Import/Export"},
		{"voodoo", "declasse", ATSTRINGHASH("muscle"), "1.30 Lowriders"},
		{"voodoo2", "declasse", ATSTRINGHASH("muscle"), "1.01 Game Launch"},
		{"vorschlaghammer", "benefactor", ATSTRINGHASH("sedan"), "1.69 Bottom Dollar Bounties"},
		{"vortex", "pegassi", ATSTRINGHASH("motorcycle"), "1.36 Bikers"},
		{"vstr", "albany", ATSTRINGHASH("sport"), "1.49 Diamond Casino Heist"},
		{"warden", "gallivan", ATSTRINGHASH("suv"), "1.73 The Kortz Center Heist"},
		{"warrener", "vulcar", ATSTRINGHASH("sedan"), "1.14 I'm Not a Hipster"},
		{"warrener2", "vulcar", ATSTRINGHASH("sedan"), "1.57 LS Tuners"},
		{"washington", "albany", ATSTRINGHASH("sedan"), "1.01 Game Launch"},
		{"wastelander", "mtl", ATSTRINGHASH("service"), "1.37 Import/Export"},
		{"weevil", "bf", ATSTRINGHASH("compacts"), "1.52 Cayo Perico Heist"},
		{"weevil2", "bf", ATSTRINGHASH("muscle"), "1.61 The Criminal Enterprises"},
		{"windsor", "enus", ATSTRINGHASH("coupe"), "1.27 Ill-Gotten Gains Part 1"},
		{"windsor2", "enus", ATSTRINGHASH("coupe"), "1.34 Further Adventures in Finance and Felony"},
		{"winky", "vapid", ATSTRINGHASH("off_road"), "1.52 Cayo Perico Heist"},
		{"wolfsbane", "western", ATSTRINGHASH("motorcycle"), "1.36 Bikers"},
		{"woodlander", "karin", ATSTRINGHASH("suv"), "1.71 Money Fronts"},
		{"xa21", "ocelot", ATSTRINGHASH("super"), "1.40 Gunrunning Pack"},
		{"xls", "benefac", ATSTRINGHASH("suv"), "1.34 Further Adventures in Finance and Felony"},
		{"xls2", "benefac", ATSTRINGHASH("suv"), "1.34 Further Adventures in Finance and Felony"},
		{"xtreme", "pfister", ATSTRINGHASH("super"), "1.72 A Safehouse in the Hills"},
		{"yosemite", "declasse", ATSTRINGHASH("muscle"), "1.42 The Doomsday Heist"},
		{"yosemite1500", "declasse", ATSTRINGHASH("off_road"), "1.69 Bottom Dollar Bounties"},
		{"yosemite2", "declasse", ATSTRINGHASH("muscle"), "1.49 Diamond Casino Heist"},
		{"yosemite3", "declasse", ATSTRINGHASH("off_road"), "1.51 LS Summer Special"},
		{"youga", "bravado", ATSTRINGHASH("van"), "1.01 Game Launch"},
		{"youga2", "bravado", ATSTRINGHASH("van"), "1.36 Bikers"},
		{"youga3", "bravado", ATSTRINGHASH("van"), "1.51 LS Summer Special"},
		{"youga4", "vapid", ATSTRINGHASH("van"), "1.58 The Contract"},
		{"youga5", "vapid", ATSTRINGHASH("van"), "1.70 Agents of Sabotage"},
		{"z190", "karin", ATSTRINGHASH("sport_classic"), "1.42 The Doomsday Heist"},
		{"zeno", "overflod", ATSTRINGHASH("super"), "1.58 The Contract"},
		{"zentorno", "pegassi", ATSTRINGHASH("super"), "1.13 High Life"},
		{"zhaba", "rune", ATSTRINGHASH("off_road"), "1.49 Diamond Casino Heist"},
		{"zion", "ubermach", ATSTRINGHASH("coupe"), "1.01 Game Launch"},
		{"zion2", "ubermach", ATSTRINGHASH("coupe"), "1.01 Game Launch"},
		{"zion3", "ubermach", ATSTRINGHASH("sport_classic"), "1.48 Diamond Casino & Resort"},
		{"zombiea", "western", ATSTRINGHASH("motorcycle"), "1.36 Bikers"},
		{"zombieb", "western", ATSTRINGHASH("motorcycle"), "1.36 Bikers"},
		{"zorrusso", "pegassi", ATSTRINGHASH("super"), "1.48 Diamond Casino & Resort"},
		{"zr350", "annis", ATSTRINGHASH("sport"), "1.57 LS Tuners"},
		{"zr380", "annis", ATSTRINGHASH("sport"), "1.46 Arena War"},
		{"zr3802", "annis", ATSTRINGHASH("sport"), "1.46 Arena War"},
		{"zr3803", "annis", ATSTRINGHASH("sport"), "1.46 Arena War"},
		{"ztype", "truffade", ATSTRINGHASH("sport_classic"), "1.01 Game Launch"},
	};
}
